class_name DriftSky
extends Node3D
## The world round a Marble Drift course: the courses float high in the sky (or in space) like shiny toy tracks,
## with an abyss far below so a fall feels deep. One theme per course (DriftCourse.theme, 0-5):
##   0 Dawn Isles     a gold dawn over a sea of cloud, floating grassy islands with trees, cloud banks
##   1 Nebula Reach   deep space: a nebula band and stars all round, a ringed gas giant and moons below, a drifting
##                    asteroid belt circling under the course
##   2 Crystal Hollow a dark cavern: giant glowing crystal clusters rising out of violet mist, floating shards
##   3 Neon Run       a synthwave sunset: a striped sun, a scrolling neon grid far below, wireframe mountains,
##                    floating neon shapes
##   4 Storm Front    a slate sky over thunderclouds: lightning flickering inside them and bolts down into them,
##                    dark floating rocks, rain
##   5 Polar Night    stars and aurora curtains over a frozen cloud sea, tall glowing ice spires
## Everything is made here from code and the shaders in ../shaders (our own designs, CC BY-SA 4.0; no third-party
## assets, nothing generated by a model).
##
## API: build(theme, course_size) makes the diorama (course_size: the course's width, height range and length; the
## course lies in x 0..W, z 0..H with floors near y 0..12). environment_for(theme) gives PopBackdrop's environment
## keys plus sky_material (the sky shader, also used for reflections), fog_height, fog_height_density, name; the view
## calls make_environment(d) and setup_sun(light, d). palette(theme) gives the course shaders' colours and
## course_materials(theme) two ready ShaderMaterials [top, side]. The abyss layers, rain and motes follow the
## current camera; everything animates in _process on the node's own clock (fixed-step safe, deterministic).

const SH := "res://games/marbledrift/shaders/"

const THEMES := [
	{   # 0 Dawn Isles
		"name": "Dawn Isles",
		"sky_top": Color("#4a6db4"), "sky_mid": Color("#c98fae"), "sky_horizon": Color("#ffc68a"),
		"sky_below": Color("#f0a87c"), "sky_deep": Color("#5a3c78"),
		"sun_dir": Vector3(-0.72, 0.3, -0.62), "sun_color": Color("#ffd29a"), "sun_energy": 1.75,
		"sun_disc": 1.0, "sun_size": 0.035, "sun_glow": 0.9,
		"ambient_color": Color("#c8a8a8"), "ambient_energy": 0.42,
		"fog_color": Color("#d8a090"), "fog_density": 0.0016, "fog_height": -16.0, "fog_height_density": 0.008,
		"fog_sun_scatter": 0.25,
		"exposure": 0.95, "glow_intensity": 0.55, "glow_threshold": 1.0, "saturation": 1.15, "contrast": 1.06,
		"night": false, "streaks": 0.6, "streak_col": Color("#ffd2b8"), "stars": 0.0, "nebula": 0.0, "aurora": 0.0,
		"synth": 0.0,
		"deck": {"y": -44.0, "lit": Color("#ffc98e"), "shade": Color("#b86c8c"), "gap": Color("#2c2052"),
			"horizon": Color("#e8a888"), "scale": 0.04, "coverage": 0.56, "contrast": 1.3, "sheen": 0.8,
			"drift": Vector2(0.05, 0.02)},
		"wisps": {"y": -27.0, "opacity": 0.4, "lit": Color("#ffe0c0"), "shade": Color("#d8a0a8")},
		"palette": {"tile_a": Color("#f7f3ea"), "tile_b": Color("#1aa0b4"), "seam": Color("#ffcf73"),
			"side": Color("#3b3456"), "accent": Color("#ffb347"), "trim": Color("#d8dce6"),
			"glass": Color("#9fe3ff"), "acid": Color("#8cff3a"), "abyss": Color("#5a3c78")},
	},
	{   # 1 Nebula Reach
		"name": "Nebula Reach",
		"sky_top": Color("#05030f"), "sky_mid": Color("#0a0820"), "sky_horizon": Color("#161033"),
		"sky_below": Color("#120b2a"), "sky_deep": Color("#04030c"),
		"sun_dir": Vector3(0.25, 0.55, 0.8), "sun_color": Color("#fff2e2"), "sun_energy": 1.8,
		"sun_disc": 1.0, "sun_size": 0.02, "sun_glow": 0.5,
		"ambient_color": Color("#4a3c86"), "ambient_energy": 0.6,
		"fog_color": Color("#120c2a"), "fog_density": 0.0008, "fog_height": -30.0, "fog_height_density": 0.004,
		"fog_sun_scatter": 0.0,
		"exposure": 1.05, "glow_intensity": 0.8, "glow_threshold": 0.9, "saturation": 1.1, "contrast": 1.05,
		"night": true, "streaks": 0.0, "streak_col": Color.WHITE, "stars": 1.0, "nebula": 1.0, "aurora": 0.0,
		"synth": 0.0, "neb_a": Color("#8a2bd8"), "neb_b": Color("#19b4c8"), "neb_axis": Vector3(0.35, 0.55, -0.75),
		"palette": {"tile_a": Color("#dfe5f4"), "tile_b": Color("#5636c6"), "seam": Color("#7ef0ff"),
			"side": Color("#181a36"), "accent": Color("#ff7ad9"), "trim": Color("#c8cce0"),
			"glass": Color("#8ad8ff"), "acid": Color("#7dff4a"), "abyss": Color("#0a0820")},
	},
	{   # 2 Crystal Hollow
		"name": "Crystal Hollow",
		"sky_top": Color("#06040f"), "sky_mid": Color("#100a22"), "sky_horizon": Color("#26163f"),
		"sky_below": Color("#1d1238"), "sky_deep": Color("#0a0618"),
		"sun_dir": Vector3(-0.4, 0.85, 0.35), "sun_color": Color("#c6b4ff"), "sun_energy": 0.85,
		"sun_disc": 0.0, "sun_size": 0.02, "sun_glow": 0.0,
		"ambient_color": Color("#4a3a7c"), "ambient_energy": 0.75,
		"fog_color": Color("#1a1030"), "fog_density": 0.0025, "fog_height": -16.0, "fog_height_density": 0.015,
		"fog_sun_scatter": 0.0,
		"exposure": 1.05, "glow_intensity": 0.85, "glow_threshold": 0.9, "saturation": 1.12, "contrast": 1.05,
		"night": true, "streaks": 0.0, "streak_col": Color.WHITE, "stars": 0.35, "nebula": 0.35, "aurora": 0.0,
		"synth": 0.0, "neb_a": Color("#5a2a9a"), "neb_b": Color("#1e8a8a"), "neb_axis": Vector3(0.0, 1.0, 0.1),
		"deck": {"y": -40.0, "lit": Color("#3a2872"), "shade": Color("#140c2c"), "gap": Color("#04020c"),
			"horizon": Color("#1a1030"), "scale": 0.045, "coverage": 0.6, "contrast": 1.1, "sheen": 0.15,
			"drift": Vector2(0.02, 0.012), "glow": 0.7, "glow_col": Color("#18b8a8"), "glow_scale": 0.012},
		"wisps": {"y": -24.0, "opacity": 0.25, "lit": Color("#8a6ad8"), "shade": Color("#3a2a6c")},
		"palette": {"tile_a": Color("#e6f4f2"), "tile_b": Color("#15a094"), "seam": Color("#c08cff"),
			"side": Color("#1d1530"), "accent": Color("#ff9be8"), "trim": Color("#cfc4e8"),
			"glass": Color("#b8a4ff"), "acid": Color("#7dff4a"), "abyss": Color("#1a1032")},
	},
	{   # 3 Neon Run
		"name": "Neon Run",
		"sky_top": Color("#100522"), "sky_mid": Color("#3a0d57"), "sky_horizon": Color("#ff5a9e"),
		"sky_below": Color("#4a0f5c"), "sky_deep": Color("#08020f"),
		"sun_dir": Vector3(-0.6, 0.12, -0.79), "sun_color": Color("#ff9ab8"), "sun_energy": 1.2,
		"sun_disc": 0.0, "sun_size": 0.02, "sun_glow": 0.0,
		"light_dir": Vector3(-0.75, 0.55, 0.35),
		"ambient_color": Color("#6a3a9a"), "ambient_energy": 0.7,
		"fog_color": Color("#3a0c50"), "fog_density": 0.0018, "fog_height": -12.0, "fog_height_density": 0.012,
		"fog_sun_scatter": 0.0,
		"exposure": 1.0, "glow_intensity": 0.9, "glow_threshold": 0.85, "saturation": 1.15, "contrast": 1.06,
		"night": true, "streaks": 0.0, "streak_col": Color.WHITE, "stars": 0.5, "nebula": 0.0, "aurora": 0.0,
		"synth": 1.0,
		"grid": {"y": -58.0, "floor": Color("#0a0214"), "a": Color("#ff2fb8"), "b": Color("#2ad8ff"),
			"horizon": Color("#5a1462")},
		"palette": {"tile_a": Color("#3a2468"), "tile_b": Color("#120c26"), "seam": Color("#3ff0ff"),
			"side": Color("#140b28"), "accent": Color("#ff3fc0"), "gloss": 0.06, "seam_energy": 3.0, "trim": Color("#8a7ab0"),
			"glass": Color("#5fe8ff"), "acid": Color("#9dff3a"), "abyss": Color("#1a0628")},
	},
	{   # 4 Storm Front
		"name": "Storm Front",
		"sky_top": Color("#141a26"), "sky_mid": Color("#252f42"), "sky_horizon": Color("#4a566c"),
		"sky_below": Color("#2a3244"), "sky_deep": Color("#080a10"),
		"sun_dir": Vector3(-0.6, 0.6, 0.5), "sun_color": Color("#c4d2e8"), "sun_energy": 1.15,
		"sun_disc": 0.0, "sun_size": 0.02, "sun_glow": 0.25,
		"ambient_color": Color("#5c6a84"), "ambient_energy": 0.7,
		"fog_color": Color("#2a3244"), "fog_density": 0.003, "fog_height": -12.0, "fog_height_density": 0.02,
		"fog_sun_scatter": 0.0,
		"exposure": 1.05, "glow_intensity": 0.7, "glow_threshold": 1.0, "saturation": 1.0, "contrast": 1.08,
		"night": false, "streaks": 0.7, "streak_col": Color("#4a5468"), "stars": 0.0, "nebula": 0.0, "aurora": 0.0,
		"synth": 0.0,
		"deck": {"y": -42.0, "lit": Color("#5c6880"), "shade": Color("#1c2230"), "gap": Color("#05070c"),
			"horizon": Color("#2a3244"), "scale": 0.04, "coverage": 0.62, "contrast": 1.4, "sheen": 0.2,
			"drift": Vector2(0.09, 0.05)},
		"wisps": {"y": -25.0, "opacity": 0.45, "lit": Color("#4a566c"), "shade": Color("#20283a")},
		"palette": {"tile_a": Color("#d8dde4"), "tile_b": Color("#e6a92a"), "seam": Color("#8fd4ff"),
			"side": Color("#252a34"), "accent": Color("#ffe066"), "trim": Color("#a8b0bc"),
			"glass": Color("#9fd8ff"), "acid": Color("#8cff3a"), "abyss": Color("#1a2030")},
	},
	{   # 5 Polar Night
		"name": "Polar Night",
		"sky_top": Color("#030918"), "sky_mid": Color("#0a1d3a"), "sky_horizon": Color("#1c4866"),
		"sky_below": Color("#123048"), "sky_deep": Color("#050c18"),
		"sun_dir": Vector3(-0.5, 0.55, 0.65), "sun_color": Color("#b0caff"), "sun_energy": 1.0,
		"sun_disc": 0.0, "sun_size": 0.02, "sun_glow": 0.0,
		"ambient_color": Color("#3c5c8a"), "ambient_energy": 0.75,
		"fog_color": Color("#0c1a30"), "fog_density": 0.002, "fog_height": -16.0, "fog_height_density": 0.012,
		"fog_sun_scatter": 0.0,
		"exposure": 1.05, "glow_intensity": 0.8, "glow_threshold": 0.9, "saturation": 1.1, "contrast": 1.05,
		"night": true, "streaks": 0.0, "streak_col": Color.WHITE, "stars": 1.0, "nebula": 0.15, "aurora": 0.7,
		"synth": 0.0, "neb_a": Color("#2a3a8a"), "neb_b": Color("#1a6a8a"), "neb_axis": Vector3(0.6, 0.6, 0.5),
		"aurora_col": Color("#3fffa0"), "aurora_dir": Vector3(-0.6, 0.0, -0.8),
		"deck": {"y": -44.0, "lit": Color("#3a5486"), "shade": Color("#0e182c"), "gap": Color("#030812"),
			"horizon": Color("#0c1a30"), "scale": 0.04, "coverage": 0.6, "contrast": 1.2, "sheen": 0.25,
			"drift": Vector2(0.03, 0.015), "glow": 0.7, "glow_col": Color("#18d080"), "glow_scale": 0.01},
		"wisps": {"y": -26.0, "opacity": 0.22, "lit": Color("#7a9ad0"), "shade": Color("#2a3a60")},
		"palette": {"tile_a": Color("#f2f7fb"), "tile_b": Color("#2a6cd4"), "seam": Color("#7dffc8"),
			"side": Color("#16233d"), "accent": Color("#b98cff"), "trim": Color("#c4d4e8"),
			"glass": Color("#a8f0ff"), "acid": Color("#8cff3a"), "abyss": Color("#0c1a30")},
	},
]

var theme := 0
var course_size := Vector3(18, 12, 56)
var _t := 0.0
var _clocked: Array = []     ## every ShaderMaterial that reads `clock`
var _follow: Array = []      ## [node, y]: abyss layers kept under the camera
var _bob: Array = []         ## [node, rest position, height, rate, phase, spin (rad/s)]
var _spin: Array = []        ## [node, local axis, rad/s]
var _focus_fx: Array = []    ## [node, offset]: particles kept round the camera's focus
var _flash_mats: Array = []  ## materials with a `flash` uniform
var _flash_light: OmniLight3D
var _bolt: MeshInstance3D
var _bolt_mesh: ImmediateMesh
var _storm_rng := RandomNumberGenerator.new()
var _next_strike := 2.5
var _strike_t := -10.0
var _strike_pos := Vector3.ZERO
var _deck_y := -40.0
var _cam_pos := Vector3(0, 30, -20)


# --- environment -----------------------------------------------------------------------------------------------

## The environment for a theme: PopBackdrop's keys (sky_top, sky_horizon, ground_horizon, ground_bottom, sun_color,
## sun_rotation, sun_energy, ambient_color, ambient_energy, fog_color, fog_density, fog_sun_scatter, exposure,
## glow_intensity, glow_threshold, saturation, contrast, night) plus sky_material (ShaderMaterial for a Sky: the
## theme's sky, also what the glossy course reflects), fog_height and fog_height_density (the abyss fog), name.
func environment_for(t: int) -> Dictionary:
	var d: Dictionary = THEMES[clampi(t, 0, THEMES.size() - 1)]
	var out := {}
	for k in ["sun_color", "sun_energy", "ambient_color", "ambient_energy", "fog_color", "fog_density",
			"fog_sun_scatter", "fog_height", "fog_height_density", "exposure", "glow_intensity", "glow_threshold",
			"saturation", "contrast", "night", "name"]:
		out[k] = d[k]
	out["sky_top"] = d["sky_top"]
	out["sky_horizon"] = d["sky_horizon"]
	out["ground_horizon"] = d["sky_below"]
	out["ground_bottom"] = d["sky_deep"]
	var l: Vector3 = (d.get("light_dir", d["sun_dir"]) as Vector3).normalized()
	out["sun_rotation"] = Vector3(rad_to_deg(asin(-l.y)), rad_to_deg(atan2(l.x, l.z)), 0.0)
	out["sky_material"] = sky_material(t)
	return out


## The theme's sky as a ShaderMaterial for a Sky resource (static: its radiance is baked once).
func sky_material(t: int) -> ShaderMaterial:
	var d: Dictionary = THEMES[clampi(t, 0, THEMES.size() - 1)]
	var m := ShaderMaterial.new()
	m.shader = load(SH + "drift_sky.gdshader")
	m.set_shader_parameter("top", d["sky_top"])
	m.set_shader_parameter("mid", d["sky_mid"])
	m.set_shader_parameter("horizon", d["sky_horizon"])
	m.set_shader_parameter("below", d["sky_below"])
	m.set_shader_parameter("deep", d["sky_deep"])
	m.set_shader_parameter("sun_dir", (d["sun_dir"] as Vector3).normalized())
	m.set_shader_parameter("sun_col", d["sun_color"])
	m.set_shader_parameter("sun_disc", d["sun_disc"])
	m.set_shader_parameter("sun_size", d["sun_size"])
	m.set_shader_parameter("sun_glow", d["sun_glow"])
	m.set_shader_parameter("synth_sun", d["synth"])
	m.set_shader_parameter("streaks", d["streaks"])
	m.set_shader_parameter("streak_col", d["streak_col"])
	m.set_shader_parameter("stars", d["stars"])
	m.set_shader_parameter("nebula", d["nebula"])
	if d.has("neb_a"):
		m.set_shader_parameter("neb_a", d["neb_a"])
		m.set_shader_parameter("neb_b", d["neb_b"])
		m.set_shader_parameter("neb_axis", d["neb_axis"])
	m.set_shader_parameter("aurora", d["aurora"])
	if d.has("aurora_col"):
		m.set_shader_parameter("aurora_col", d["aurora_col"])
		m.set_shader_parameter("aurora_dir", d["aurora_dir"])
	return m


## A ready Environment from environment_for()'s dictionary (the view may use it as is or copy the values).
static func make_environment(d: Dictionary) -> Environment:
	var env := Environment.new()
	var sky := Sky.new()
	if d.has("sky_material"):
		sky.sky_material = d["sky_material"]
	else:
		var sm := ProceduralSkyMaterial.new()
		sm.sky_top_color = d["sky_top"]
		sm.sky_horizon_color = d["sky_horizon"]
		sm.ground_horizon_color = d["ground_horizon"]
		sm.ground_bottom_color = d["ground_bottom"]
		sky.sky_material = sm
	sky.radiance_size = Sky.RADIANCE_SIZE_128
	env.sky = sky
	env.background_mode = Environment.BG_SKY
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = d["ambient_color"]
	env.ambient_light_energy = d["ambient_energy"]
	env.reflected_light_source = Environment.REFLECTION_SOURCE_SKY
	env.tonemap_mode = Environment.TONE_MAPPER_ACES
	env.tonemap_exposure = d["exposure"]
	env.tonemap_white = 6.0
	env.fog_enabled = true
	env.fog_mode = Environment.FOG_MODE_EXPONENTIAL
	env.fog_light_color = d["fog_color"]
	env.fog_density = d["fog_density"]
	env.fog_sun_scatter = d["fog_sun_scatter"]
	env.fog_sky_affect = 0.0
	env.fog_height = d.get("fog_height", 0.0)
	env.fog_height_density = d.get("fog_height_density", 0.0)
	env.glow_enabled = true
	env.glow_intensity = d["glow_intensity"]
	env.glow_hdr_threshold = d["glow_threshold"]
	env.glow_bloom = 0.04
	env.glow_blend_mode = Environment.GLOW_BLEND_MODE_SOFTLIGHT
	env.set_glow_level(2, 1.0)
	env.set_glow_level(3, 0.8)
	env.set_glow_level(4, 0.6)
	env.set_glow_level(5, 0.3)
	env.ssr_enabled = d.get("ssr", false)   # optional: the tiles mirror the walls and the marble (costly)
	env.ssr_max_steps = 48
	env.ssr_fade_in = 0.1
	env.ssr_fade_out = 3.0
	env.ssr_depth_tolerance = 0.4
	env.adjustment_enabled = true
	env.adjustment_saturation = d["saturation"]
	env.adjustment_contrast = d["contrast"]
	return env


static func setup_sun(sun: DirectionalLight3D, d: Dictionary) -> void:
	sun.rotation_degrees = d["sun_rotation"]
	sun.light_color = d["sun_color"]
	sun.light_energy = d["sun_energy"]
	sun.light_specular = 0.6
	sun.shadow_enabled = true
	sun.shadow_blur = 1.5
	sun.directional_shadow_max_distance = 70.0


## The course shaders' settings for a theme. Every key is a uniform of course_top.gdshader and/or
## course_side.gdshader with the same name, so a view can copy them all in (set_shader_parameter(k, v) for each key
## on both materials; a key the shader lacks is ignored): tile_a, tile_b (the chequer), seam (the glowing seams and
## side strips), side (cliff panels), accent (goal lights, wall trim band), trim (wall tops), glass, acid, abyss
## (where the sides fade to), and for some themes gloss and seam_energy (floats).
func palette(t: int) -> Dictionary:
	return (THEMES[clampi(t, 0, THEMES.size() - 1)]["palette"] as Dictionary).duplicate()


## Ready materials for the course mesh: [top (course_top.gdshader), side (course_side.gdshader)], set from palette().
## fade_top / fade_bottom: the world heights where the sides start and finish fading into the abyss.
func course_materials(t: int, fade_top := -2.0, fade_bottom := -14.0) -> Array[ShaderMaterial]:
	var p := palette(t)
	var top := ShaderMaterial.new()
	top.shader = load(SH + "course_top.gdshader")
	var side := ShaderMaterial.new()
	side.shader = load(SH + "course_side.gdshader")
	for k in p:
		top.set_shader_parameter(k, p[k])
		side.set_shader_parameter(k, p[k])
	side.set_shader_parameter("fade_top", fade_top)
	side.set_shader_parameter("fade_bottom", fade_bottom)
	return [top, side]


# --- building --------------------------------------------------------------------------------------------------

## Builds the diorama for a theme round a course of the given size (x across, y the height range, z its length).
func build(t: int, size := Vector3(18, 12, 56)) -> void:
	for c in get_children():
		remove_child(c)
		c.queue_free()
	theme = clampi(t, 0, THEMES.size() - 1)
	course_size = size
	_t = 0.0
	_clocked.clear()
	_follow.clear()
	_bob.clear()
	_spin.clear()
	_focus_fx.clear()
	_flash_mats.clear()
	_flash_light = null
	_bolt = null
	_storm_rng.seed = 4700 + theme
	_next_strike = 2.5
	_strike_t = -10.0
	var d: Dictionary = THEMES[theme]
	if d.has("deck"):
		_add_deck(d)
	if d.has("grid"):
		_add_grid(d)
	var rng := RandomNumberGenerator.new()
	rng.seed = 2700 + theme * 31
	match theme:
		0: _build_dawn(d, rng)
		1: _build_space(d, rng)
		2: _build_cavern(d, rng)
		3: _build_synth(d, rng)
		4: _build_storm(d, rng)
		5: _build_polar(d, rng)
	_cam_pos = Vector3(size.x * 0.5 - 20.0, 30.0, -20.0)
	_place_follow()


func _centre() -> Vector3:
	return Vector3(course_size.x * 0.5, 0.0, course_size.z * 0.5)


func _shader(n: String, clocked := true) -> ShaderMaterial:
	var m := ShaderMaterial.new()
	m.shader = load(SH + n + ".gdshader")
	if clocked:
		_clocked.append(m)
	return m


func _mi(nm: String, mesh: Mesh, mat: Material, pos: Vector3, shadow := false) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	mi.name = nm
	mi.mesh = mesh
	mi.material_override = mat
	mi.position = pos
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_ON if shadow else GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	mi.gi_mode = GeometryInstance3D.GI_MODE_DISABLED
	add_child(mi)
	return mi


## A random spot round the course for a distant object, mostly on the side the game's camera looks towards (it sits
## at +x +z of the marble looking back up the course, towards -x -z): beside a point along the course, `clear` to
## `clear + reach` away, at a height between y1 (near) and y0 (far). Never right under the course.
func _spot(rng: RandomNumberGenerator, clear: float, reach: float, y0: float, y1: float) -> Vector3:
	var along := rng.randf_range(-40.0, course_size.z + 30.0)
	var a := deg_to_rad(-135.0) + rng.randf_range(-1.0, 1.0) * deg_to_rad(120.0)
	var k := pow(rng.randf(), 0.8)
	var off := clear + k * reach
	var hw := course_size.x * 0.5
	var p := Vector3(hw + sin(a) * (hw + off), 0.0, along + cos(a) * off)
	if absf(p.x - hw) < hw + clear and p.z > -clear and p.z < course_size.z + clear:
		p.x = hw + signf(p.x - hw + 0.01) * (hw + clear + k * reach * 0.5)
	p.y = lerpf(y1, y0, clampf(k * 0.7 + rng.randf() * 0.3, 0.0, 1.0))
	return p


func _add_deck(d: Dictionary) -> void:
	var k: Dictionary = d["deck"]
	_deck_y = k["y"]
	var sd := (d["sun_dir"] as Vector3).normalized()
	var m := _shader("drift_deck")
	m.set_shader_parameter("lit_col", k["lit"])
	m.set_shader_parameter("shade_col", k["shade"])
	m.set_shader_parameter("gap_col", k["gap"])
	m.set_shader_parameter("horizon_col", k["horizon"])
	m.set_shader_parameter("sun_dir", sd)
	m.set_shader_parameter("sun_col", d["sun_color"])
	m.set_shader_parameter("scale", k["scale"])
	m.set_shader_parameter("coverage", k["coverage"])
	m.set_shader_parameter("contrast", k["contrast"])
	m.set_shader_parameter("sheen", k["sheen"])
	m.set_shader_parameter("drift", k["drift"])
	m.set_shader_parameter("glow", k.get("glow", 0.0))
	m.set_shader_parameter("glow_col", k.get("glow_col", Color.WHITE))
	m.set_shader_parameter("glow_scale", k.get("glow_scale", 0.004))
	m.render_priority = -2
	_flash_mats.append(m)
	var plane := PlaneMesh.new()
	plane.size = Vector2(2400, 2400)
	var deck := _mi("abyss_deck", plane, m, Vector3(0, _deck_y, 0))
	_follow.append([deck, _deck_y])
	if d.has("wisps"):
		var w: Dictionary = d["wisps"]
		var wm := _shader("drift_deck")
		wm.set_shader_parameter("lit_col", w["lit"])
		wm.set_shader_parameter("shade_col", w["shade"])
		wm.set_shader_parameter("gap_col", w["shade"])
		wm.set_shader_parameter("horizon_col", k["horizon"])
		wm.set_shader_parameter("sun_dir", sd)
		wm.set_shader_parameter("sun_col", d["sun_color"])
		wm.set_shader_parameter("scale", (k["scale"] as float) * 1.6)
		wm.set_shader_parameter("coverage", 0.38)
		wm.set_shader_parameter("contrast", 0.8)
		wm.set_shader_parameter("sheen", (k["sheen"] as float) * 0.8)
		wm.set_shader_parameter("drift", (k["drift"] as Vector2) * 1.8)
		wm.set_shader_parameter("gap_alpha", 0.0)
		wm.set_shader_parameter("opacity", w["opacity"])
		wm.set_shader_parameter("detail_oct", 3.0)
		wm.set_shader_parameter("light_oct", 0.0)
		wm.set_shader_parameter("fade_near", 80.0)
		wm.set_shader_parameter("fade_far", 420.0)
		wm.render_priority = -1
		_flash_mats.append(wm)
		var wp := PlaneMesh.new()
		wp.size = Vector2(1200, 1200)
		var wisp := _mi("abyss_wisps", wp, wm, Vector3(0, w["y"], 0))
		_follow.append([wisp, w["y"]])


func _add_grid(d: Dictionary) -> void:
	var g: Dictionary = d["grid"]
	_deck_y = g["y"]
	var m := _shader("drift_grid")
	m.set_shader_parameter("floor_col", g["floor"])
	m.set_shader_parameter("line_a", g["a"])
	m.set_shader_parameter("line_b", g["b"])
	m.set_shader_parameter("horizon_col", g["horizon"])
	m.set_shader_parameter("sun_dir", (d["sun_dir"] as Vector3).normalized())
	m.set_shader_parameter("sun_col", Color("#ff6a9a"))
	m.set_shader_parameter("energy", 0.9)
	m.set_shader_parameter("spacing", 8.0)
	var plane := PlaneMesh.new()
	plane.size = Vector2(2400, 2400)
	var grid := _mi("abyss_grid", plane, m, Vector3(0, _deck_y, 0))
	_follow.append([grid, _deck_y])


# --- theme 0: Dawn Isles ---------------------------------------------------------------------------------------

func _build_dawn(d: Dictionary, rng: RandomNumberGenerator) -> void:
	var mat := _vc_material(0.88)
	for i in 16:
		var r := rng.randf_range(3.0, 12.0) if i > 2 else rng.randf_range(12.0, 18.0)
		var p := _spot(rng, 22.0 + r, 110.0, -38.0, -12.0)
		if i < 3:
			p = _spot(rng, 60.0, 80.0, -36.0, -26.0)
		var mesh := _island_mesh(rng, r, Color("#6cbf3c"), Color("#9a5a36"), Color("#8a6458"), int(r * 0.9),
				Color("#3f8a3a"), true)
		var isl := _mi("island_%d" % i, mesh, mat, p)
		isl.rotation.y = rng.randf() * TAU
		_bob.append([isl, p, 0.3 + r * 0.03, 0.12 + rng.randf() * 0.1, rng.randf() * TAU, 0.0])
	var cm := _cloud_material(d, Color("#ffd8aa"), Color("#b87890"), 0.9)
	cm.set_shader_parameter("puffiness", 1.4)
	_add_cloud_banks(rng, 6, cm, -42.0, -34.0)
	_add_motes(Color(1.0, 0.85, 0.55, 0.5), 90, 0.12, Vector3(30, 14, 30))


# --- theme 1: Nebula Reach -------------------------------------------------------------------------------------

func _build_space(d: Dictionary, rng: RandomNumberGenerator) -> void:
	var c := _centre()
	var sd := (d["sun_dir"] as Vector3).normalized()
	# the ringed gas giant, low ahead and to the right
	var gp := c + Vector3(-290.0, -330.0, -250.0)
	var gr := 105.0
	_planet("giant", gp, gr, Color("#e8b07a"), Color("#8a4a3a"), Color("#fbe6c8"), Color("#ffb070"), 7.0, sd, 0.9)
	var ring := _shader("drift_ring", false)
	ring.set_shader_parameter("col_a", Color("#f0dcc0"))
	ring.set_shader_parameter("col_b", Color("#8a6a5a"))
	ring.set_shader_parameter("sun_dir", sd)
	ring.set_shader_parameter("planet_centre", gp)
	ring.set_shader_parameter("planet_radius", gr)
	var rm := _mi("giant_ring", _annulus(gr * 1.3, gr * 2.3, 128), ring, gp)
	rm.rotation = Vector3(deg_to_rad(18.0), deg_to_rad(-25.0), deg_to_rad(12.0))
	# a cratered moon and a far icy world
	_planet("moon", c + Vector3(-70.0, -90.0, -40.0), 14.0, Color("#b8b0a8"), Color("#5a5450"), Color("#e8e4dc"),
			Color("#9ab0d0"), 0.0, sd, 0.3)
	_planet("ice_world", c + Vector3(110.0, -230.0, -330.0), 36.0, Color("#8ad0f0"), Color("#2a5a9a"),
			Color("#e8f8ff"), Color("#6ab8ff"), 4.0, sd, 1.2)
	# the asteroid belt circling under the course
	var belt := Node3D.new()
	belt.name = "belt"
	belt.position = c + Vector3(0.0, -48.0, 10.0)
	belt.rotation = Vector3(deg_to_rad(8.0), 0.0, deg_to_rad(-6.0))
	add_child(belt)
	_spin.append([belt, Vector3.UP, 0.012])
	var rock := _vc_material(0.8)
	for v in 3:
		var mesh := _rock_mesh(rng, Color("#6a5e58"), Color("#221c22"), 1.0)
		var mm := MultiMesh.new()
		mm.transform_format = MultiMesh.TRANSFORM_3D
		mm.mesh = mesh
		mm.instance_count = 140
		for i in mm.instance_count:
			var a := rng.randf() * TAU
			var rad := rng.randf_range(70.0, 150.0) + (rng.randf() - 0.5) * 20.0
			var y := (rng.randf() + rng.randf() - 1.0) * 7.0
			var s := pow(rng.randf(), 3.0) * 3.0 + 0.3
			var b := Basis.from_euler(Vector3(rng.randf() * TAU, rng.randf() * TAU, rng.randf() * TAU)).scaled(Vector3.ONE * s)
			mm.set_instance_transform(i, Transform3D(b, Vector3(cos(a) * rad, y, sin(a) * rad)))
		var mmi := MultiMeshInstance3D.new()
		mmi.name = "belt_%d" % v
		mmi.multimesh = mm
		mmi.material_override = rock
		mmi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		belt.add_child(mmi)
	# big lonely rocks closer in, tumbling slowly (they give the parallax)
	for i in 10:
		var p := _spot(rng, 16.0, 70.0, -40.0, -10.0)
		var big := _mi("rock_%d" % i, _rock_mesh(rng, Color("#857670"), Color("#2a2228"), rng.randf_range(1.5, 4.0)),
				rock, p)
		big.rotation = Vector3(rng.randf() * TAU, rng.randf() * TAU, 0.0)
		_bob.append([big, p, 0.8, 0.08 + rng.randf() * 0.08, rng.randf() * TAU, 0.05 + rng.randf() * 0.1])
	_add_motes(Color(0.7, 0.8, 1.0, 0.35), 70, 0.08, Vector3(34, 16, 34))


func _planet(nm: String, pos: Vector3, r: float, a: Color, b: Color, cc: Color, atmo: Color, bands: float,
		sd: Vector3, atmo_k: float) -> void:
	var m := _shader("drift_planet")
	m.set_shader_parameter("col_a", a)
	m.set_shader_parameter("col_b", b)
	m.set_shader_parameter("col_c", cc)
	m.set_shader_parameter("atmo", atmo)
	m.set_shader_parameter("atmo_strength", atmo_k)
	m.set_shader_parameter("bands", bands)
	m.set_shader_parameter("sun_dir", sd)
	var s := SphereMesh.new()
	s.radius = r
	s.height = r * 2.0
	s.radial_segments = 96
	s.rings = 48
	_mi(nm, s, m, pos)


func _annulus(r0: float, r1: float, seg: int) -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for i in seg:
		var a0 := TAU * i / seg
		var a1 := TAU * (i + 1) / seg
		var p00 := Vector3(cos(a0) * r0, 0, sin(a0) * r0)
		var p01 := Vector3(cos(a0) * r1, 0, sin(a0) * r1)
		var p10 := Vector3(cos(a1) * r0, 0, sin(a1) * r0)
		var p11 := Vector3(cos(a1) * r1, 0, sin(a1) * r1)
		for q in [[p00, 0.0], [p01, 1.0], [p11, 1.0], [p00, 0.0], [p11, 1.0], [p10, 0.0]]:
			st.set_normal(Vector3.UP)
			st.set_uv(Vector2(q[1], 0.0))
			st.add_vertex(q[0])
	return st.commit()


# --- theme 2: Crystal Hollow -----------------------------------------------------------------------------------

func _build_cavern(d: Dictionary, rng: RandomNumberGenerator) -> void:
	var looks := [
		[Color("#1a0a30"), Color("#a05aff"), Color("#9ff0ff")],
		[Color("#06201e"), Color("#22d8b8"), Color("#d4fff4")],
		[Color("#2a0a24"), Color("#ff5ad0"), Color("#ffd0f4")],
	]
	var mats: Array = []
	for l in looks:
		var m := _shader("drift_crystal")
		m.set_shader_parameter("shell", l[0])
		m.set_shader_parameter("core", l[1])
		m.set_shader_parameter("tip", l[2])
		m.set_shader_parameter("energy", 0.9)
		m.set_shader_parameter("veins", 0.0)
		mats.append(m)
	# great clusters rising out of the mist
	for i in 14:
		var p := _spot(rng, 14.0, 110.0, -58.0, -46.0)
		var hgt := rng.randf_range(26.0, 52.0) * (1.0 if i > 3 else 1.3)
		var mesh := _crystal_cluster(rng, hgt, rng.randf_range(3.0, 6.5), rng.randi_range(4, 8), 6, 0.0)
		var cl := _mi("crystals_%d" % i, mesh, mats[i % 3], p)
		cl.rotation.y = rng.randf() * TAU
	# clusters hanging from the cavern's roof, far off
	for i in 6:
		var p := _spot(rng, 40.0, 120.0, 70.0, 55.0)
		var mesh := _crystal_cluster(rng, rng.randf_range(20.0, 36.0), 4.0, 5, 6, 0.0)
		var cl := _mi("hanging_%d" % i, mesh, mats[(i + 1) % 3], p)
		cl.rotation = Vector3(PI, rng.randf() * TAU, 0.0)
	# shards floating near the course
	for i in 18:
		var p := _spot(rng, 4.0, 40.0, -26.0, -3.0)
		var mesh := _crystal_cluster(rng, rng.randf_range(1.5, 4.0), 0.6, 1, 6, 0.0, true)
		var sh := _mi("shard_%d" % i, mesh, mats[i % 3], p)
		sh.rotation = Vector3(rng.randf_range(-0.5, 0.5), rng.randf() * TAU, rng.randf_range(-0.5, 0.5))
		_bob.append([sh, p, 0.6, 0.25 + rng.randf() * 0.2, rng.randf() * TAU, 0.2 + rng.randf() * 0.3])
	# dark rock pillars far out, so the hollow has walls
	var rock := _vc_material(0.9)
	for i in 8:
		var p := _spot(rng, 90.0, 120.0, -60.0, -60.0)
		var pil := _mi("pillar_%d" % i, _rock_mesh(rng, Color("#2e2440"), Color("#120c1c"), 1.0), rock, p)
		pil.scale = Vector3(rng.randf_range(10.0, 18.0), rng.randf_range(60.0, 90.0), rng.randf_range(10.0, 18.0))
	_add_motes(Color(0.5, 1.0, 0.9, 0.6), 120, 0.1, Vector3(30, 14, 30))


## A cluster of faceted crystals with pointed tips (UV.y 0 base .. 1 tip; COLOR.r phase, COLOR.g brightness).
func _crystal_cluster(rng: RandomNumberGenerator, hgt: float, rad: float, count: int, sides: int, jag: float,
		single := false) -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for c in count:
		var h := hgt * (1.0 if c == 0 else rng.randf_range(0.35, 0.8))
		var r := rad * (1.0 if c == 0 else rng.randf_range(0.35, 0.7)) * (h / hgt) ** 0.3
		var tilt := Basis()
		var base := Vector3.ZERO
		if c > 0:
			tilt = Basis(Vector3(rng.randf() - 0.5, 0, rng.randf() - 0.5).normalized(), rng.randf_range(0.2, 0.6))
			base = Vector3(rng.randf_range(-1, 1), 0, rng.randf_range(-1, 1)) * rad * 0.9
		if single:
			base = Vector3(0, -h * 0.5, 0)
		var col := Color(rng.randf(), rng.randf_range(0.7, 1.1), 0)
		var shoulder := h - r * 1.8
		var ring0: Array = []
		var ring1: Array = []
		var off := rng.randf() * TAU
		for s in sides:
			var a := off + TAU * s / sides
			var j := 1.0 + jag * (rng.randf() - 0.5)
			ring0.append(base + tilt * Vector3(cos(a) * r * j, 0, sin(a) * r * j))
			ring1.append(base + tilt * Vector3(cos(a) * r * 0.86 * j, shoulder, sin(a) * r * 0.86 * j))
		var apex := base + tilt * Vector3(r * 0.1, h, 0)
		var axis := base + tilt * Vector3(0, h * 0.5, 0)
		var v0 := 0.0
		var v1 := shoulder / h
		for s in sides:
			var n := (s + 1) % sides
			_tri_uv(st, [ring0[s], ring1[s], ring1[n]], [v0, v1, v1], axis, col)
			_tri_uv(st, [ring0[s], ring1[n], ring0[n]], [v0, v1, v0], axis, col)
			_tri_uv(st, [ring1[s], apex, ring1[n]], [v1, 1.0, v1], axis, col)
			if single:
				var bottom := base + tilt * Vector3(0, -r * 1.6, 0)
				_tri_uv(st, [ring0[s], ring0[n], bottom], [v0, v0, 0.0], axis, col)
	return st.commit()


## One triangle with the outward-facing winding (Godot's front faces are clockwise) and its face normal.
func _tri_uv(st: SurfaceTool, p: Array, v: Array, inside: Vector3, col: Color) -> void:
	var a: Vector3 = p[0]
	var b: Vector3 = p[1]
	var c: Vector3 = p[2]
	var va: float = v[0]
	var vb: float = v[1]
	var vc: float = v[2]
	var n := (c - a).cross(b - a)
	if n.dot((a + b + c) / 3.0 - inside) < 0.0:
		var tb := b
		b = c
		c = tb
		var tv := vb
		vb = vc
		vc = tv
		n = -n
	n = n.normalized()
	for q in [[a, va], [b, vb], [c, vc]]:
		st.set_normal(n)
		st.set_color(col)
		st.set_uv(Vector2(0.0, q[1]))
		st.add_vertex(q[0])


# --- theme 3: Neon Run -----------------------------------------------------------------------------------------

func _build_synth(d: Dictionary, rng: RandomNumberGenerator) -> void:
	var g: Dictionary = d["grid"]
	var wire := _shader("drift_neon")
	wire.set_shader_parameter("line_a", g["a"])
	wire.set_shader_parameter("line_b", g["b"])
	wire.set_shader_parameter("energy", 1.3)
	wire.set_shader_parameter("fill", 0.05)
	# a ring of wireframe mountains on the grid, open towards the camera
	var c := _centre()
	var ridge := _mountain_ring(rng, c, 170.0, 270.0, (g["y"] as float), deg_to_rad(-250.0), deg_to_rad(-20.0))
	_mi("mountains", ridge, wire, Vector3.ZERO)
	# floating neon shapes near the course
	var shapes: Array = []
	shapes.append(_wire_mesh(_octa(1.0)))
	shapes.append(_wire_mesh(_torus_arrays(1.0, 0.25, 20, 6)))
	shapes.append(_wire_mesh(_pyramid(1.0)))
	var mats := [wire]
	var wire2 := _shader("drift_neon")
	wire2.set_shader_parameter("line_a", g["b"])
	wire2.set_shader_parameter("line_b", Color("#fff07a"))
	wire2.set_shader_parameter("energy", 2.6)
	mats.append(wire2)
	for i in 16:
		var p := _spot(rng, 6.0, 60.0, -24.0, -2.0)
		var s := rng.randf_range(1.5, 5.0)
		var sh := _mi("shape_%d" % i, shapes[i % 3], mats[i % 2], p)
		sh.scale = Vector3.ONE * s
		sh.rotation = Vector3(rng.randf() * TAU, rng.randf() * TAU, 0)
		_bob.append([sh, p, 0.8, 0.2 + rng.randf() * 0.2, rng.randf() * TAU, 0.2 + rng.randf() * 0.4])
	_add_motes(Color(1.0, 0.4, 0.9, 0.5), 60, 0.08, Vector3(30, 14, 30))


func _mountain_ring(rng: RandomNumberGenerator, c: Vector3, r0: float, r1: float, y0: float, a0: float,
		a1: float) -> ArrayMesh:
	var cols := 72
	var rows := 7
	var noise := FastNoiseLite.new()
	noise.seed = rng.randi()
	noise.frequency = 0.12
	var pts: Array = []
	for j in rows + 1:
		var row: Array = []
		var f := float(j) / rows
		for i in cols + 1:
			var a := lerpf(a0, a1, float(i) / cols)
			var r := lerpf(r0, r1, f)
			# peaks: tallest in the middle rows, a sharp ridge line
			var ridge := 1.0 - absf(f - 0.55) * 2.0
			var h := maxf(0.0, ridge) * (10.0 + 34.0 * absf(noise.get_noise_2d(i * 1.0, j * 1.6)) + 16.0 * absf(noise.get_noise_2d(i * 3.1, 7.0)))
			if j == 0 or j == rows:
				h = 0.0
			# the axis: forward (+z) is angle 0
			row.append(c + Vector3(sin(a) * r, y0 + h, cos(a) * r))
		pts.append(row)
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for j in rows:
		for i in cols:
			var p00: Vector3 = pts[j][i]
			var p10: Vector3 = pts[j][i + 1]
			var p01: Vector3 = pts[j + 1][i]
			var p11: Vector3 = pts[j + 1][i + 1]
			_bary_tri(st, p00, p10, p11, y0, 70.0)
			_bary_tri(st, p00, p11, p01, y0, 70.0)
	return st.commit()


func _bary_tri(st: SurfaceTool, a: Vector3, b: Vector3, c: Vector3, y0: float, span: float) -> void:
	var n := (c - a).cross(b - a).normalized()
	var cols := [Color(1, 0, 0), Color(0, 1, 0), Color(0, 0, 1)]
	var ps := [a, b, c]
	for k in 3:
		st.set_normal(n)
		st.set_color(cols[k])
		st.set_uv(Vector2(0.0, clampf(((ps[k] as Vector3).y - y0) / span, 0.0, 1.0)))
		st.add_vertex(ps[k])


## An indexed triangle soup [vertices, indices] made into an unindexed wireframe-ready mesh.
func _wire_mesh(arr: Array) -> ArrayMesh:
	var vs: PackedVector3Array = arr[0]
	var ix: PackedInt32Array = arr[1]
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var lo := INF
	var hi := -INF
	for v in vs:
		lo = minf(lo, v.y)
		hi = maxf(hi, v.y)
	for t in range(0, ix.size(), 3):
		_bary_tri(st, vs[ix[t]], vs[ix[t + 1]], vs[ix[t + 2]], lo, maxf(hi - lo, 0.001))
	return st.commit()


func _octa(r: float) -> Array:
	var vs := PackedVector3Array([Vector3(r, 0, 0), Vector3(-r, 0, 0), Vector3(0, r * 1.4, 0), Vector3(0, -r * 1.4, 0),
			Vector3(0, 0, r), Vector3(0, 0, -r)])
	var ix := PackedInt32Array([0, 2, 4, 4, 2, 1, 1, 2, 5, 5, 2, 0, 0, 4, 3, 4, 1, 3, 1, 5, 3, 5, 0, 3])
	return [vs, ix]


func _pyramid(r: float) -> Array:
	var vs := PackedVector3Array([Vector3(-r, -r * 0.6, -r), Vector3(r, -r * 0.6, -r), Vector3(r, -r * 0.6, r),
			Vector3(-r, -r * 0.6, r), Vector3(0, r, 0)])
	var ix := PackedInt32Array([0, 1, 4, 1, 2, 4, 2, 3, 4, 3, 0, 4, 0, 2, 1, 0, 3, 2])
	return [vs, ix]


func _torus_arrays(r: float, rr: float, seg: int, sides: int) -> Array:
	var vs := PackedVector3Array()
	var ix := PackedInt32Array()
	for i in seg:
		var a := TAU * i / seg
		for j in sides:
			var b := TAU * j / sides
			vs.append(Vector3(cos(a) * (r + rr * cos(b)), rr * sin(b), sin(a) * (r + rr * cos(b))))
	for i in seg:
		for j in sides:
			var a0 := i * sides + j
			var a1 := ((i + 1) % seg) * sides + j
			var b0 := i * sides + (j + 1) % sides
			var b1 := ((i + 1) % seg) * sides + (j + 1) % sides
			ix.append_array([a0, a1, b1, a0, b1, b0])
	return [vs, ix]


# --- theme 4: Storm Front --------------------------------------------------------------------------------------

func _build_storm(d: Dictionary, rng: RandomNumberGenerator) -> void:
	# dark floating rocks, tumbling slowly
	var mat := _vc_material(0.85)
	for i in 12:
		var r := rng.randf_range(2.0, 6.0)
		var p := _spot(rng, 18.0 + r, 90.0, -38.0, -14.0)
		var rock := _mi("rock_%d" % i, _rock_mesh(rng, Color("#5a5e6a"), Color("#1c1e26"), r), mat, p)
		rock.rotation = Vector3(rng.randf() * TAU, rng.randf() * TAU, 0.0)
		_bob.append([rock, p, 0.5, 0.12 + rng.randf() * 0.1, rng.randf() * TAU, 0.04 + rng.randf() * 0.06])
	# rain round the camera's focus
	var rain := _particles("rain", 900, 1.1, Vector3(36, 1, 36), 1, 1.0, Vector2(0.025, 1.6))
	var pm: ParticleProcessMaterial = rain[1]
	pm.direction = Vector3(0.12, -1, 0.05)
	pm.spread = 2.0
	pm.initial_velocity_min = 34.0
	pm.initial_velocity_max = 42.0
	pm.gravity = Vector3(0, -10, 0)
	pm.particle_flag_align_y = true
	pm.color = Color(0.7, 0.8, 1.0, 0.28)
	_focus_fx.append([rain[0], Vector3(0, 22, 0)])
	# lightning: a bolt mesh and a flash light
	_bolt_mesh = ImmediateMesh.new()
	var bm := StandardMaterial3D.new()
	bm.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	bm.blend_mode = BaseMaterial3D.BLEND_MODE_ADD
	bm.albedo_color = Color(2.2, 2.4, 3.2)
	bm.cull_mode = BaseMaterial3D.CULL_DISABLED
	bm.no_depth_test = false
	bm.disable_fog = true
	_bolt = _mi("bolt", _bolt_mesh, bm, Vector3.ZERO)
	_bolt.visible = false
	_flash_light = OmniLight3D.new()
	_flash_light.name = "flash"
	_flash_light.light_color = Color("#c8d8ff")
	_flash_light.light_energy = 0.0
	_flash_light.omni_range = 140.0
	_flash_light.omni_attenuation = 0.8
	add_child(_flash_light)


func _cloud_material(d: Dictionary, lit: Color, shade: Color, opacity: float) -> ShaderMaterial:
	var m := _shader("drift_cloud")
	m.set_shader_parameter("lit", lit)
	m.set_shader_parameter("shade", shade)
	m.set_shader_parameter("sun_dir", (d["sun_dir"] as Vector3).normalized())
	m.set_shader_parameter("sun_col", d["sun_color"])
	m.set_shader_parameter("opacity", opacity)
	_flash_mats.append(m)
	return m


## Camera-facing cloud sprites as one MultiMesh: puffs = [[offset, width, height], ...] round pos.
func _cloud_sprites(nm: String, rng: RandomNumberGenerator, pos: Vector3, puffs: Array, m: ShaderMaterial) -> Node3D:
	var q := QuadMesh.new()
	q.size = Vector2(1, 1)
	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.use_colors = true
	mm.mesh = q
	mm.instance_count = puffs.size()
	for i in puffs.size():
		var pf: Array = puffs[i]
		mm.set_instance_transform(i, Transform3D(Basis().scaled(Vector3(pf[1], pf[2], 1.0)), pf[0]))
		mm.set_instance_color(i, Color(rng.randf(), rng.randf(), 0))
	var mmi := MultiMeshInstance3D.new()
	mmi.name = nm
	mmi.multimesh = mm
	mmi.material_override = m
	mmi.position = pos
	mmi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	mmi.custom_aabb = AABB(Vector3(-80, -40, -80), Vector3(160, 160, 160))
	add_child(mmi)
	return mmi


## Banks of soft cloud floating just above the deck.
func _add_cloud_banks(rng: RandomNumberGenerator, banks: int, m: ShaderMaterial, y0: float, y1: float) -> void:
	for b in banks:
		var p := _spot(rng, 18.0, 110.0, y0, y1)
		var puffs: Array = []
		for i in 6:
			var w := rng.randf_range(16.0, 30.0)
			puffs.append([Vector3(rng.randf_range(-1, 1) * 22.0, rng.randf() * 4.0 + i * 0.5, rng.randf_range(-1, 1) * 14.0),
					w, w * 0.55])
		var node := _cloud_sprites("clouds_%d" % b, rng, p, puffs, m)
		_bob.append([node, p, 0.5, 0.05, rng.randf() * TAU, 0.0])


# --- theme 5: Polar Night --------------------------------------------------------------------------------------

func _build_polar(d: Dictionary, rng: RandomNumberGenerator) -> void:
	var ice := _shader("drift_crystal")
	ice.set_shader_parameter("shell", Color("#14284a"))
	ice.set_shader_parameter("core", Color("#2a7ad8"))
	ice.set_shader_parameter("tip", Color("#a8ffe0"))
	ice.set_shader_parameter("energy", 1.0)
	ice.set_shader_parameter("frost", 0.2)
	ice.set_shader_parameter("roughness", 0.06)
	ice.set_shader_parameter("pulse", 0.12)
	ice.set_shader_parameter("veins", 0.3)
	for i in 14:
		var p := _spot(rng, 20.0, 120.0, -66.0, -56.0)
		var hgt := rng.randf_range(30.0, 62.0)
		var mesh := _crystal_cluster(rng, hgt, rng.randf_range(2.5, 5.0), rng.randi_range(1, 4), 5, 0.35)
		var sp := _mi("spire_%d" % i, mesh, ice, p)
		sp.rotation.y = rng.randf() * TAU
	# aurora curtains far ahead and to the sides
	var c := _centre()
	var curtains := [
		[c + Vector3(-150.0, -40.0, -110.0), 320.0, 140.0, 0.78, Color("#3fffa0"), Color("#7a3aff")],
		[c + Vector3(-125.0, -38.0, 60.0), 240.0, 120.0, 1.35, Color("#2affd0"), Color("#ff4aa0")],
		[c + Vector3(-10.0, -38.0, -150.0), 240.0, 120.0, 0.2, Color("#6aff7a"), Color("#4a6aff")],
	]
	for i in curtains.size():
		var cu: Array = curtains[i]
		var m := _shader("drift_aurora")
		m.set_shader_parameter("low", cu[4])
		m.set_shader_parameter("high", cu[5])
		m.set_shader_parameter("seed", float(i) * 3.7)
		m.set_shader_parameter("energy", 0.7)
		var rib := _mi("aurora_%d" % i, _ribbon(rng, cu[1], cu[2]), m, cu[0])
		rib.rotation.y = cu[3]
	_add_motes(Color(0.8, 0.95, 1.0, 0.7), 220, 0.07, Vector3(32, 16, 32), Vector3(0.3, -0.6, 0.1))


func _ribbon(rng: RandomNumberGenerator, length: float, hgt: float) -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var seg := 96
	var ph := rng.randf() * TAU
	var pts: Array = []
	for i in seg + 1:
		var u := float(i) / seg
		var x := (u - 0.5) * length
		var z := sin(u * 7.0 + ph) * length * 0.05 + sin(u * 17.0 + ph * 2.0) * length * 0.015
		pts.append(Vector3(x, 0, z))
	for i in seg:
		var u0 := float(i) / seg
		var u1 := float(i + 1) / seg
		var a: Vector3 = pts[i]
		var b: Vector3 = pts[i + 1]
		var quad := [[a, u0, 0.0], [b, u1, 0.0], [b + Vector3(0, hgt, 0), u1, 1.0],
				[a, u0, 0.0], [b + Vector3(0, hgt, 0), u1, 1.0], [a + Vector3(0, hgt, 0), u0, 1.0]]
		for q in quad:
			st.set_normal(Vector3.BACK)
			st.set_uv(Vector2(q[1], q[2]))
			st.add_vertex(q[0])
	return st.commit()


# --- shared pieces ---------------------------------------------------------------------------------------------

func _vc_material(rough: float) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.vertex_color_use_as_albedo = true
	m.roughness = rough
	m.rim_enabled = true
	m.rim = 0.35
	m.rim_tint = 0.6
	return m


## A floating island: a domed grassy top with a soil lip and a long jagged rock underside ending in a point, with
## optional little trees. Faceted (flat-shaded), coloured by vertex.
func _island_mesh(rng: RandomNumberGenerator, r: float, grass: Color, soil: Color, rock: Color, trees: int,
		leaf: Color, deep := true) -> ArrayMesh:
	var noise := FastNoiseLite.new()
	noise.seed = rng.randi()
	noise.frequency = 0.35
	var seg := 22
	# rings: [radius fraction, height (in r), kind 0 grass 1 soil 2 rock]
	var rings := [[0.35, 0.16, 0], [0.7, 0.1, 0], [1.0, 0.0, 0], [1.02, -0.18, 1], [0.92, -0.42, 2],
			[0.74, -0.75, 2], [0.5, -1.1, 2], [0.26, -1.45, 2]]
	if not deep:
		rings = [[0.35, 0.12, 0], [0.7, 0.07, 0], [1.0, 0.0, 1], [1.02, -0.2, 2], [0.86, -0.5, 2], [0.55, -0.85, 2],
				[0.25, -1.1, 2]]
	var pts: Array = []
	var kinds: Array = []
	for ri in rings.size():
		var ring: Array = []
		for s in seg:
			var a := TAU * s / seg
			var jag := 1.0 + 0.22 * noise.get_noise_2d(cos(a) * 3.0, sin(a) * 3.0 + ri * 1.7)
			var rr: float = rings[ri][0] * r * jag
			var y: float = rings[ri][1] * r + 0.12 * r * noise.get_noise_2d(cos(a) * 5.0 + ri, sin(a) * 5.0)
			ring.append(Vector3(cos(a) * rr, y, sin(a) * rr))
		pts.append(ring)
		kinds.append(rings[ri][2])
	var top := Vector3(0, r * 0.2, 0)
	var tip := Vector3(r * 0.1, -r * (1.9 if deep else 1.4), 0)
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var cols := [grass, soil, rock]
	for s in seg:
		var n := (s + 1) % seg
		_tri(st, top, pts[0][s], pts[0][n], Vector3(0, -r * 2.0, 0), _vary(rng, grass, 0.06))
		for ri in rings.size() - 1:
			var k: int = kinds[ri + 1]
			var col: Color = cols[k]
			if k == 2:
				col = col * (0.82 + 0.18 * sin((pts[ri + 1][s] as Vector3).y * 2.2 / maxf(r * 0.1, 0.3)))
			var inside := Vector3(0, (pts[ri][s] as Vector3).y, 0)
			_tri(st, pts[ri][s], pts[ri + 1][s], pts[ri + 1][n], inside, _vary(rng, col, 0.08))
			_tri(st, pts[ri][s], pts[ri + 1][n], pts[ri][n], inside, _vary(rng, col, 0.08))
		_tri(st, pts[rings.size() - 1][s], tip, pts[rings.size() - 1][n], Vector3(0, tip.y * 0.5, 0),
				_vary(rng, rock * 0.75, 0.08))
	# little trees: a trunk and two stacked cones
	for i in trees:
		var a := rng.randf() * TAU
		var d := sqrt(rng.randf()) * r * 0.6
		var base := Vector3(cos(a) * d, r * 0.12 * (1.0 - d / r) + 0.02 * r, sin(a) * d)
		var th := rng.randf_range(1.6, 3.0)
		_cone(st, base, 0.18, th * 0.4, 5, Color("#6a4a34"))
		_cone(st, base + Vector3(0, th * 0.3, 0), th * 0.38, th * 0.7, 7, _vary(rng, leaf, 0.12))
		_cone(st, base + Vector3(0, th * 0.62, 0), th * 0.26, th * 0.55, 7, _vary(rng, leaf * 1.15, 0.12))
	return st.commit()


func _cone(st: SurfaceTool, base: Vector3, r: float, h: float, sides: int, col: Color) -> void:
	var apex := base + Vector3(0, h, 0)
	var inside := base + Vector3(0, h * 0.3, 0)
	for s in sides:
		var a0 := TAU * s / sides
		var a1 := TAU * (s + 1) / sides
		var p0 := base + Vector3(cos(a0) * r, 0, sin(a0) * r)
		var p1 := base + Vector3(cos(a1) * r, 0, sin(a1) * r)
		_tri(st, p0, apex, p1, inside, col)


func _vary(rng: RandomNumberGenerator, c: Color, k: float) -> Color:
	var f := 1.0 + (rng.randf() - 0.5) * 2.0 * k
	return Color(c.r * f, c.g * f, c.b * f)


func _tri(st: SurfaceTool, a: Vector3, b: Vector3, c: Vector3, inside: Vector3, col: Color) -> void:
	_tri_uv(st, [a, b, c], [0.0, 0.0, 0.0], inside, col)


## A lumpy faceted rock (radius about r), coloured from light to dark by height.
func _rock_mesh(rng: RandomNumberGenerator, light: Color, dark: Color, r: float) -> ArrayMesh:
	var sm := SphereMesh.new()
	sm.radius = 1.0
	sm.height = 2.0
	sm.radial_segments = 10
	sm.rings = 6
	var arr := sm.get_mesh_arrays()
	var vs: PackedVector3Array = arr[Mesh.ARRAY_VERTEX]
	var ix: PackedInt32Array = arr[Mesh.ARRAY_INDEX]
	var noise := FastNoiseLite.new()
	noise.seed = rng.randi()
	noise.frequency = 1.3
	var squash := Vector3(rng.randf_range(0.8, 1.3), rng.randf_range(0.6, 1.0), rng.randf_range(0.8, 1.3))
	var moved := PackedVector3Array()
	for v in vs:
		var k := 1.0 + 0.35 * noise.get_noise_3dv(v * 1.0)
		moved.append(v * k * squash * r)
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for t in range(0, ix.size(), 3):
		var a := moved[ix[t]]
		var b := moved[ix[t + 1]]
		var c := moved[ix[t + 2]]
		if a.distance_to(b) < 1e-4 or b.distance_to(c) < 1e-4 or a.distance_to(c) < 1e-4:
			continue
		var y := ((a + b + c) / 3.0).y / (r * squash.y)
		_tri(st, a, b, c, Vector3.ZERO, _vary(rng, dark.lerp(light, clampf(0.5 + y * 0.5, 0.0, 1.0)), 0.1))
	return st.commit()


## Particles kept round the camera's focus: [GPUParticles3D, ParticleProcessMaterial].
func _particles(nm: String, amount: int, life: float, box: Vector3, shape: int, emit: float, size: Vector2) -> Array:
	var p := GPUParticles3D.new()
	p.name = nm
	p.amount = amount
	p.lifetime = life
	p.preprocess = life
	p.fixed_fps = 30
	p.use_fixed_seed = true
	p.seed = 47 + theme
	p.local_coords = false
	p.visibility_aabb = AABB(-box - Vector3(20, 60, 20), (box + Vector3(20, 60, 20)) * 2.0)
	p.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	var pm := ParticleProcessMaterial.new()
	pm.emission_shape = ParticleProcessMaterial.EMISSION_SHAPE_BOX
	pm.emission_box_extents = box
	var q := QuadMesh.new()
	q.size = size
	var m := _shader("drift_particle", false)
	m.set_shader_parameter("shape", shape)
	m.set_shader_parameter("emit", emit)
	q.material = m
	p.draw_pass_1 = q
	p.process_material = pm
	add_child(p)
	return [p, pm]


func _add_motes(col: Color, amount: int, size: float, box: Vector3, grav := Vector3(0, 0.05, 0)) -> void:
	var r := _particles("motes", amount, 9.0, box, 0, 2.0, Vector2(size, size))
	var pm: ParticleProcessMaterial = r[1]
	pm.gravity = grav
	pm.initial_velocity_min = 0.05
	pm.initial_velocity_max = 0.3
	pm.direction = Vector3(0, 1, 0)
	pm.spread = 180.0
	pm.turbulence_enabled = true
	pm.turbulence_noise_strength = 0.4
	pm.turbulence_noise_scale = 4.0
	pm.color = col
	pm.scale_min = 0.5
	pm.scale_max = 1.5
	var ramp := Gradient.new()
	ramp.set_color(0, Color(1, 1, 1, 0))
	ramp.add_point(0.2, Color(1, 1, 1, 1))
	ramp.add_point(0.8, Color(1, 1, 1, 1))
	ramp.set_color(ramp.get_point_count() - 1, Color(1, 1, 1, 0))
	var gt := GradientTexture1D.new()
	gt.gradient = ramp
	pm.color_ramp = gt
	_focus_fx.append([r[0], Vector3(0, 4, 0)])


# --- animation -------------------------------------------------------------------------------------------------

func _place_follow() -> void:
	var cam := get_viewport().get_camera_3d() if is_inside_tree() else null
	if cam:
		_cam_pos = cam.global_position
	for f in _follow:
		var node: Node3D = f[0]
		node.position = Vector3(_cam_pos.x, f[1], _cam_pos.z)   # the backdrop sits at the origin
	if cam and not _focus_fx.is_empty():
		var fwd := -cam.global_transform.basis.z
		# where the view meets the course's height: roughly the marble
		var tt := clampf((cam.global_position.y - 4.0) / maxf(-fwd.y, 0.2), 5.0, 60.0)
		var focus := cam.global_position + fwd * tt
		for f in _focus_fx:
			(f[0] as Node3D).global_position = focus + (f[1] as Vector3)


func _process(delta: float) -> void:
	_t += delta
	for m in _clocked:
		(m as ShaderMaterial).set_shader_parameter("clock", _t)
	for b in _bob:
		var node: Node3D = b[0]
		var rest: Vector3 = b[1]
		var ph: float = _t * b[3] + b[4]
		node.position = rest + Vector3(0, sin(ph) * b[2], 0)
		if b[5] != 0.0:
			node.rotate_y(b[5] * delta)
	for s in _spin:
		(s[0] as Node3D).rotate_object_local(s[1], s[2] * delta)
	_place_follow()
	if _flash_light:
		_storm(delta)


## Lightning: every few seconds a strike somewhere in view below the course; the bolt flickers, the clouds and the
## towers light up from inside, the flash light catches the cliffs.
func _storm(_delta: float) -> void:
	if _t >= _next_strike:
		_strike_t = _t
		_next_strike = _t + _storm_rng.randf_range(2.5, 6.5)
		# somewhere in view: beyond the course from the camera (which looks towards -x -z), off to a side
		var a := deg_to_rad(-135.0) + _storm_rng.randf_range(-0.9, 0.9)
		var r := _storm_rng.randf_range(35.0, 90.0)
		_strike_pos = Vector3(_cam_pos.x + sin(a) * r, _deck_y, _cam_pos.z + cos(a) * r)
		_make_bolt()
	var age := _t - _strike_t
	var f := 0.0
	if age < 0.6:
		# two or three flickers
		f = exp(-age * 7.0) + 0.7 * exp(-pow((age - 0.18) * 30.0, 2.0)) + 0.5 * exp(-pow((age - 0.34) * 26.0, 2.0))
	var fl := Vector4(_strike_pos.x, _strike_pos.z, 45.0, f * 1.0)
	for m in _flash_mats:
		(m as ShaderMaterial).set_shader_parameter("flash", fl)
	_flash_light.position = _strike_pos + Vector3(0, 20, 0)
	_flash_light.light_energy = f * 3.0
	_bolt.visible = f > 0.25


func _make_bolt() -> void:
	var cam := get_viewport().get_camera_3d()
	var to_cam := (cam.global_position - _strike_pos).normalized() if cam else Vector3.BACK
	_bolt_mesh.clear_surfaces()
	_bolt_mesh.surface_begin(Mesh.PRIMITIVE_TRIANGLES)
	var top := _strike_pos + Vector3(_storm_rng.randf_range(-10, 10), _storm_rng.randf_range(26.0, 40.0), 0)
	_bolt_branch(top, _strike_pos + Vector3(0, -2, 0), 0.5, 16, to_cam)
	for b in 2:
		var from := top.lerp(_strike_pos, _storm_rng.randf_range(0.2, 0.5))
		var to := from + Vector3(_storm_rng.randf_range(-14, 14), -_storm_rng.randf_range(8, 16), _storm_rng.randf_range(-6, 6))
		_bolt_branch(from, to, 0.25, 7, to_cam)
	_bolt_mesh.surface_end()


func _bolt_branch(a: Vector3, b: Vector3, w: float, steps: int, to_cam: Vector3) -> void:
	var prev := a
	for i in steps:
		var f := float(i + 1) / steps
		var p := a.lerp(b, f)
		if i < steps - 1:
			p += Vector3(_storm_rng.randf_range(-1, 1), _storm_rng.randf_range(-0.3, 0.3), _storm_rng.randf_range(-1, 1)) * 2.4
		var dir := (p - prev).normalized()
		var side := dir.cross(to_cam).normalized() * w * (1.0 - 0.5 * f)
		for v in [prev - side, prev + side, p + side, prev - side, p + side, p - side]:
			_bolt_mesh.surface_add_vertex(v)
		prev = p
