#!/usr/bin/env python3
"""Generate godot/games/glimmerdeep/engine/cave_properties.gd from GDash (MIT): the BDCFF cave properties, their
types and their default values (CaveStored::descriptor and CaveStored::set_gdash_defaults).

Usage: python3 tools/gdash_port/gen_properties.py [path/to/gdash]   (default: .tools/ref/gdash)
"""
import re, sys, pathlib

src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".tools/ref/gdash") / "src/cave"
stored = (src / "cavestored.cpp").read_text()
types = (src / "cavetypes.hpp").read_text()

def enum_list(name):
    body = re.search(r"enum %s \{(.*?)\};" % name, types, re.S).group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    out = {}
    i = 0
    for item in [x.strip() for x in body.split(",") if x.strip()]:
        if "=" in item:
            n, v = [p.strip() for p in item.split("=")]
            i = out[v] if v in out else int(v, 0)
            out[n] = i
        else:
            out[item] = i
        i += 1
    return out

consts = {}
consts.update(enum_list("GdElementEnum"))
consts.update(enum_list("GdDirectionEnum"))
consts.update(enum_list("GdSchedulingEnum"))

# --- descriptor: first array, until {NULL}
desc_src = stored[stored.index("PropertyDescription const CaveStored::descriptor[]"):]
desc_src = desc_src[:desc_src.index("\n};")]
desc = []
for m in re.finditer(r'\{"([^"]*)",\s*(GD_TYPE_[A-Z_]+),\s*([^,]*),.*?GetterBase::create_new\(&CaveStored::(\w+)\)', desc_src):
    ident, typ, flags, member = m.groups()
    desc.append((ident, typ[8:], flags.strip(), member))

members = {}
for ident, typ, flags, member in desc:
    members.setdefault(member, typ)

# --- defaults
body = stored[stored.index("void CaveStored::set_gdash_defaults() {"):]
body = body[:body.index("\n};")]
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
body = re.sub(r"//[^\n]*", "", body)
values = {}

def value(expr, i=None):
    expr = expr.strip()
    m = re.match(r"GdColor::from_c64\((\d+)\)", expr)
    if m:
        return ("color", int(m.group(1)))
    if expr in ("true", "false"):
        return expr == "true"
    if expr in consts:
        return consts[expr]
    if expr == "i":
        return i
    if expr == "i + 1":
        return i + 1
    return int(expr)

pos = 0
lines = body.split("\n")
k = 0
while k < len(lines):
    line = lines[k].strip()
    m = re.match(r"for \(unsigned i = 0; i < 5; i\+\+\)\s*(\{)?\s*(.*)$", line)
    if m:
        block = []
        if m.group(1):
            k += 1
            while lines[k].strip() != "}":
                block.append(lines[k].strip()); k += 1
        else:
            k += 1
            block.append(lines[k].strip())
        for i in range(5):
            for b in block:
                mm = re.match(r"(\w+)\[i\] = (.*);", b)
                if mm:
                    values.setdefault(mm.group(1), [None] * 5)[i] = value(mm.group(2), i)
        k += 1
        continue
    mm = re.match(r"(\w+)\[(\d)\] = (.*);", line)
    if mm:
        values.setdefault(mm.group(1), [None] * 5)[int(mm.group(2))] = value(mm.group(3))
    else:
        mm = re.match(r"(\w+) = (.*);", line)
        if mm:
            values[mm.group(1)] = value(mm.group(2))
    k += 1

GD = {"STRING": "String", "LONGSTRING": "String", "BOOLEAN": "bool", "INT": "int", "PROBABILITY": "int",
      "ELEMENT": "int", "EFFECT": "int", "DIRECTION": "int", "SCHEDULING": "int", "COLOR": "String",
      "INT_LEVELS": "Array[int]", "PROBABILITY_LEVELS": "Array[int]"}
ZERO = {"String": '""', "bool": "false", "int": "0", "Array[int]": "[0, 0, 0, 0, 0]"}

def gd_value(v, t):
    if isinstance(v, tuple):
        return '"C64:%d"' % v[1]
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, list):
        return "[" + ", ".join(str(x) for x in v) + "]"
    return str(v)

L = ["# Generated by tools/gdash_port/gen_properties.py from GDash (src/cave/cavestored.cpp). Do not edit by hand.",
     "#",
     "# Property list and defaults derived from GDash, Copyright (c) 2007-2013, Czirkos Zoltan (MIT licence,",
     "# see GDASH_LICENSE.txt). Modifications are GPL-3.0-or-later.",
     "class_name CaveProperties",
     "extends RefCounted",
     "## Every BDCFF cave property, with the GDash (= BDCFF) default value. Levels arrays hold the 5 difficulty levels.",
     "## Probabilities are integers in millionths. Colors keep the text from the file (\"C64:n\" for defaults).",
     ""]
for member, typ in members.items():
    t = GD[typ]
    v = gd_value(values[member], t) if member in values else ZERO[t]
    L.append(f"var {member}: {t} = {v}")
L.append("")
L.append("## [BDCFF identifier, type, member, flags]. Several rows can share an identifier: their words are read in order.")
L.append("const DESCRIPTORS := [")
for ident, typ, flags, member in desc:
    L.append(f'\t["{ident}", "{typ}", "{member}", "{flags}"],')
L.append("]")
L.append("")
L.append("const MEMBERS: Array[String] = [" + ", ".join(f'"{m}"' for m in members) + "]")
L.append("")
L.append("""
## Copies every property from another CaveProperties (arrays are duplicated).
func copy_properties_from(other: CaveProperties) -> void:
	for m in MEMBERS:
		var v = other.get(m)
		set(m, v.duplicate() if v is Array else v)
""".strip("\n"))
out = pathlib.Path("godot/games/glimmerdeep/engine/cave_properties.gd")
out.write_text("\n".join(L) + "\n")
missing = [m for m in members if m not in values]
print(f"wrote {out}: {len(members)} properties, {len(desc)} descriptor rows; no default for: {missing}")
