#!/usr/bin/env python3
"""Generate godot/games/glimmerdeep/engine/cave_elements.gd from the GDash sources (MIT).

Usage: python3 tools/gdash_port/gen_elements.py [path/to/gdash]   (default: .tools/ref/gdash)
The GDash checkout is not part of the repo; see tools/gdash_port/README.md.
"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".tools/ref/gdash") / "src/cave"
types = (root / "cavetypes.hpp").read_text()
props_h = (root / "elementproperties.hpp").read_text()
props_c = (root / "elementproperties.cpp").read_text()

# element enum, in order
body = re.search(r"enum GdElementEnum \{(.*?)\};", types, re.S).group(1)
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
body = re.sub(r"//[^\n]*", "", body)
names = [n.strip() for n in body.split(",") if n.strip()]
index = {n: i for i, n in enumerate(names)}

# property bits
bits = {}
e_order = re.search(r"enum ElementPropertyEnum \{(.*?)\};", props_h, re.S).group(1)
e_order = [re.sub(r"//.*", "", l).strip().rstrip(",") for l in e_order.splitlines()]
e_order = [l for l in e_order if l]
for i, n in enumerate(e_order):
    bits["P_" + n[4:]] = 1 << i
bits["P_SLOPED"] = bits["P_SLOPED_LEFT"] | bits["P_SLOPED_RIGHT"] | bits["P_SLOPED_UP"] | bits["P_SLOPED_DOWN"]

def flags(expr):
    expr = expr.strip()
    if expr == "0":
        return 0
    v = 0
    for part in expr.split("|"):
        v |= bits[part.strip()]
    return v

# property table entries: { ... },
table = re.search(r"gd_element_properties\[\] = \{(.*)\n\};", props_c, re.S).group(1)
table = re.sub(r"/\*.*?\*/", "", table, flags=re.S)
entries = re.findall(r"\{(.*?)\}\s*,", table, re.S)

def split_args(s):
    out, cur, q = [], "", None
    i = 0
    while i < len(s):
        c = s[i]
        if q:
            cur += c
            if c == "\\":
                cur += s[i + 1]; i += 1
            elif c == q:
                q = None
        elif c in "\"'":
            q = c; cur += c
        elif c == ",":
            out.append(cur.strip()); cur = ""
        else:
            cur += c
        i += 1
    if cur.strip():
        out.append(cur.strip())
    return out

def cstr(s):
    s = s.strip()
    m = re.match(r'N_\((.*)\)$', s)
    if m:
        s = m.group(1)
    if s in ("0", "NULL"):
        return ""
    return bytes(s[1:-1], "utf-8").decode("unicode_escape")

def cchar(s):
    s = s.strip()
    if s == "0":
        return ""
    return bytes(s[1:-1], "utf-8").decode("unicode_escape")

rows = {}
for e in entries:
    a = split_args(e.replace("\n", " "))
    el = a[0]
    if el not in index or len(a) < 6:
        continue
    rows[index[el]] = dict(
        pair=index[a[1]], visible=cstr(a[2]), flags=flags(a[3]), file=cstr(a[4]),
        char=cchar(a[5]), ckdelay=int(a[9]) if len(a) > 9 else 0)

o_max = index["O_MAX"]
missing = [names[i] for i in range(o_max) if i not in rows]
assert not missing, missing

def ident(n):
    return n[2:].upper()

L = ["# Generated by tools/gdash_port/gen_elements.py from GDash (src/cave/cavetypes.hpp, elementproperties.*).",
     "# Do not edit by hand.",
     "#",
     "# Element list and properties derived from GDash, Copyright (c) 2007-2013, Czirkos Zoltan (MIT licence,",
     "# see godot/games/glimmerdeep/engine/GDASH_LICENSE.txt). Modifications are GPL-3.0-or-later.",
     "class_name CaveElements",
     "extends RefCounted",
     ""]
for n, v in bits.items():
    L.append(f"const {n} := {v}")
L.append("")
for i, n in enumerate(names):
    L.append(f"const {ident(n)} := {i}")
L.append("")
L.append(f"const COUNT := {o_max}  ## elements that can be in a cave (O_MAX)")
L.append("")
def arr(kind, vals):
    return f"const {kind} = " + "[" + ", ".join(vals) + "]"
L.append(arr("PAIR: Array[int]", [str(rows[i]["pair"]) for i in range(o_max)]))
L.append(arr("FLAGS: Array[int]", [str(rows[i]["flags"]) for i in range(o_max)]))
L.append(arr("CKDELAY: Array[int]", [str(rows[i]["ckdelay"]) for i in range(o_max)]))
def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
L.append("## Name in BDCFF files, like \"BOULDER\".")
L.append(arr("FILE_NAME: Array[String]", [q(rows[i]["file"]) for i in range(o_max)]))
L.append("## Character in BDCFF [map] sections, like \"r\" (empty if none).")
L.append(arr("MAP_CHAR: Array[String]", [q(rows[i]["char"]) for i in range(o_max)]))
L.append(arr("VISIBLE_NAME: Array[String]", [q(rows[i]["visible"]) for i in range(o_max)]))
L.append("")
L.append("""
static func has(element: int, flag: int) -> bool:
	return (FLAGS[element] & flag) != 0


static func is_scanned(element: int) -> bool:
	return (FLAGS[element] & P_SCANNED) != 0


static func scanned_pair(element: int) -> int:
	return element if (FLAGS[element] & P_SCANNED) != 0 else PAIR[element]


static func nonscanned_pair(element: int) -> int:
	return element if (FLAGS[element] & P_SCANNED) == 0 else PAIR[element]
""".strip("\n"))
out = pathlib.Path("godot/games/glimmerdeep/engine/cave_elements.gd")
out.write_text("\n".join(L) + "\n")
print(f"wrote {out}: {o_max} elements, {len(bits)} flags")
